/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/Akustik.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { UseCustomization } from '../context/ColorContext';

export function Akustik({props}) {
  const { nodes } = useGLTF('/Akustik.glb')
  const ColorContext = UseCustomization()
  const {Tuner, Neck, Nut, Fret, FretBoard, Body, Bridge, BridgeNut} = ColorContext;

  const txt = useTexture({
    map: './PavingStones092_1K_Color.jpg',
    displacementMap: './PavingStones092_1K_Displacement.jpg',
    normalMap: './PavingStones092_1K_NormalGL.jpg',
    roughnessMap: './PavingStones092_1K_Roughness.jpg',
    aoMap: './PavingStones092_1K_AmbientOcclusion.jpg',
  })

  console.log(txt)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body.geometry} material={nodes.Body.material} position={[-0.014, -0.784, 0.431]} rotation={[Math.PI / 2, 0, 0]}>
        <meshStandardMaterial {...props} color={Body.color} displacementScale={0.0000001}{...txt}/>
      </mesh>
      <mesh geometry={nodes.Neck.geometry} material={nodes.Neck.material} position={[0.042, 0.432, -0.19]}>
        <meshStandardMaterial {...props} color={Neck.color} displacementScale={0.0000001}{...txt}/>
      </mesh>
      <mesh geometry={nodes.Bridge.geometry} material={nodes.Bridge.material} position={[0.086, -1.536, -0.19]}>
        <meshStandardMaterial {...props} color={Bridge.color}/>
      </mesh>
      <mesh geometry={nodes.FretBoard.geometry} material={nodes.FretBoard.material} position={[0.071, 1.464, -0.454]}>
        <meshStandardMaterial {...props} color={FretBoard.color}/>
      </mesh>
      <mesh geometry={nodes.Nut.geometry} material={nodes.Nut.material} position={[0.1, 1.886, -0.033]}>
        <meshStandardMaterial {...props} color={Nut.color}/>
      </mesh>
      <mesh geometry={nodes.BridgeNut1.geometry} material={nodes.BridgeNut1.material} position={[-0.144, -1.645, 0.463]}>
        <meshStandardMaterial {...props} color={BridgeNut.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.557, 0.119, 0.274]}>
      <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Tuner.geometry} material={nodes.Tuner.material} position={[-0.373, 1.878, 0.748]}>
      <meshStandardMaterial {...props} color={Tuner.color}/>
      </mesh>
      <mesh geometry={nodes.Fret1.geometry} material={nodes.Fret1.material} position={[-0.016, -0.137, -0.04]}>
      <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[-0.016, -0.08, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder003.geometry} material={nodes.Cylinder003.material} position={[-0.016, -0.022, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[-0.016, 0.048, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder005.geometry} material={nodes.Cylinder005.material} position={[-0.016, 0.119, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder006.geometry} material={nodes.Cylinder006.material} position={[-0.016, 0.193, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder007.geometry} material={nodes.Cylinder007.material} position={[-0.016, 0.271, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder008.geometry} material={nodes.Cylinder008.material} position={[-0.016, 0.354, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder009.geometry} material={nodes.Cylinder009.material} position={[-0.016, 0.443, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder010.geometry} material={nodes.Cylinder010.material} position={[-0.016, 0.538, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder011.geometry} material={nodes.Cylinder011.material} position={[-0.016, 0.638, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder012.geometry} material={nodes.Cylinder012.material} position={[-0.016, 0.743, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder013.geometry} material={nodes.Cylinder013.material} position={[-0.016, 0.853, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[-0.016, 0.972, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} position={[-0.016, 1.095, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} position={[-0.016, 1.226, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Fret5.geometry} material={nodes.Fret5.material} position={[-0.016, 1.364, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Fret4.geometry} material={nodes.Fret4.material} position={[-0.016, 1.513, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Fret3.geometry} material={nodes.Fret3.material} position={[-0.016, 1.668, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.Fret2.geometry} material={nodes.Fret2.material} position={[-0.016, 1.833, -0.04]}>
        <meshStandardMaterial {...props} color={Fret.color}/>
      </mesh>
      <mesh geometry={nodes.BridgeNut2.geometry} material={nodes.BridgeNut2.material} position={[-2.062, -1.324, 0.113]}>
        <meshStandardMaterial {...props} color={BridgeNut.color}/>
      </mesh>
    </group>
  )
}

export default Akustik;
useGLTF.preload('/Akustik.glb')
