/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Akustik_Gibson.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { UseCustomization } from "../context/ColorContext";
import { UseTexture } from "../context/TextureContext";
import { useRef, useEffect } from "react";
import { TextureLoader } from "three";

export function Akustik_Gibson(props) {
  const { nodes } = useGLTF("/Akustik_Gibson.glb");
  const { Tuner, Neck, Nut, Fret, FretBoard, Body, Bridge, BridgeNut } =
    UseCustomization();
  const bridgenut = useRef();
  const fret = useRef();
  const bridge = useRef();
  const nut = useRef();
  const body = useRef();
  const neck = useRef();
  const tuner = useRef();
  const fretboard = useRef();
  const materials = useRef();
  const {
    TunerTxt,
    FretTxt,
    FretBoardTxt,
    NeckTxt,
    NutTxt,
    BodyTxt,
    BridgeTxt,
    BridgeNutTxt,
  } = UseTexture();

  useEffect(() => {
    const loadTexture = async () => {
      if (TunerTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(TunerTxt);
          tuner.current.map = texture;
          tuner.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [TunerTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NeckTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NeckTxt);
          neck.current.map = texture;
          neck.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NeckTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BodyTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BodyTxt);
          body.current.map = texture;
          body.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BodyTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretBoardTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretBoardTxt);
          fretboard.current.map = texture;
          fretboard.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [FretBoardTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretTxt);
          fret.current.map = texture;
          fret.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [FretTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NutTxt);
          nut.current.map = texture;
          nut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeNutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeNutTxt);
          bridgenut.current.map = texture;
          bridgenut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeNutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeTxt);
          bridge.current.map = texture;
          bridge.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeTxt]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Body.geometry}
        material={materials.Body}
        position={[-0.033, -0.753, 0.265]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color={Body.color} ref={body} {...props} />
      </mesh>
      <mesh
        geometry={nodes.Neck.geometry}
        material={materials.Neck}
        position={[-0.038, -0.26, 0.265]}
      >
        <meshStandardMaterial color={Neck.color} ref={neck} {...props} />
      </mesh>
      <mesh
        geometry={nodes.Bridge.geometry}
        material={materials.Bridge}
        position={[-0.022, -1.456, 0.279]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color={Bridge.color} ref={bridge} {...props} />
      </mesh>
      <mesh
        geometry={nodes.BridgeNut.geometry}
        material={materials.BridgeNut}
        position={[-0.172, -1.49, 0.231]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial
          color={BridgeNut.color}
          ref={bridgenut}
          {...props}
        />
      </mesh>
      <mesh
        geometry={nodes.Tuner.geometry}
        material={materials.Tuner}
        position={[-2.164, 1.535, 0.204]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial color={Tuner.color} ref={tuner} {...props} />
      </mesh>
      <mesh
        geometry={nodes.FretBoard.geometry}
        material={materials.FretBoard}
        position={[-0.039, -0.025, 0.298]}
      >
        <meshStandardMaterial
          color={FretBoard.color}
          ref={fretboard}
          {...props}
        />
      </mesh>
      <mesh
        geometry={nodes.Nut.geometry}
        material={materials.Nut}
        position={[-0.039, 1.637, 0.304]}
      >
        <meshStandardMaterial color={Nut.color} ref={nut} {...props} />
      </mesh>
      <mesh
        geometry={nodes.Fret.geometry}
        material={materials.Fret}
        position={[-0.04, -0.348, 0.307]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <meshStandardMaterial color={Fret.color} ref={fret} {...props} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/Akustik_Gibson.glb");
export default Akustik_Gibson;
