/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Akustik_Yamaha.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { UseCustomization } from "../context/ColorContext";
import { UseTexture } from "../context/TextureContext";
import { useRef, useEffect } from "react";
import { TextureLoader } from "three";

export function Akustik_Yamaha(props) {
  const { nodes } = useGLTF("/Akustik_Yamaha.glb");
  const { Tuner, Neck, Nut, Fret, FretBoard, Body, Bridge, BridgeNut } =
    UseCustomization();
  const bridgenut = useRef();
  const fret = useRef();
  const bridge = useRef();
  const nut = useRef();
  const body = useRef();
  const neck = useRef();
  const tuner = useRef();
  const fretboard = useRef();
  const materials = useRef();
  const {
    TunerTxt,
    FretTxt,
    FretBoardTxt,
    NeckTxt,
    NutTxt,
    BodyTxt,
    BridgeTxt,
    BridgeNutTxt,
  } = UseTexture();

  useEffect(() => {
    const loadTexture = async () => {
      if (TunerTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(TunerTxt);
          tuner.current.map = texture;
          tuner.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [TunerTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NeckTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NeckTxt);
          neck.current.map = texture;
          neck.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NeckTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BodyTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BodyTxt);
          body.current.map = texture;
          body.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BodyTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretBoardTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretBoardTxt);
          fretboard.current.map = texture;
          fretboard.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [FretBoardTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretTxt);
          fret.current.map = texture;
          fret.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [FretTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NutTxt);
          nut.current.map = texture;
          nut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeNutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeNutTxt);
          bridgenut.current.map = texture;
          bridgenut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeNutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeTxt);
          bridge.current.map = texture;
          bridge.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeTxt]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Body.geometry}
        material={materials.Body}
        position={[0.07, -0.828, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial {...props} color={Body.color} ref={body} />
      </mesh>
      <mesh
        geometry={nodes.Neck.geometry}
        material={materials.Neck}
        position={[0, 0.887, 0.007]}
      >
        <meshStandardMaterial {...props} color={Neck.color} ref={neck} />
      </mesh>
      <mesh
        geometry={nodes.Bridge.geometry}
        material={materials.Bridge}
        position={[-0.037, -1.103, 0.045]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial {...props} color={Bridge.color} ref={bridge} />
      </mesh>
      <mesh
        geometry={nodes.BridgeNut.geometry}
        material={materials.BridgeNut}
        position={[-0.007, -0.975, 0.073]}
        rotation={[Math.PI / 2, 0.054, 0]}
      >
        <meshStandardMaterial
          {...props}
          color={BridgeNut.color}
          ref={bridgenut}
        />
      </mesh>
      <mesh
        geometry={nodes.FretBoard.geometry}
        material={materials.FretBoard}
        position={[0, 0.279, 0.091]}
      >
        <meshStandardMaterial
          {...props}
          color={FretBoard.color}
          ref={fretboard}
        />
      </mesh>
      <mesh
        geometry={nodes.Nut.geometry}
        material={materials.Nut}
        position={[-0.004, 1.817, 0.086]}
      >
        <meshStandardMaterial {...props} color={Nut.color} ref={nut} />
      </mesh>
      <mesh
        geometry={nodes.Tuner.geometry}
        material={materials.Tuner}
        position={[-0.079, 2.22, -0.12]}
        rotation={[1.368, 0, 0]}
      >
        <meshStandardMaterial {...props} color={Tuner.color} ref={tuner} />
      </mesh>
      <mesh
        geometry={nodes.Fret.geometry}
        material={materials.Fret}
        position={[-0.004, -0.057, 0.092]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <meshStandardMaterial {...props} color={Fret.color} ref={fret} />
      </mesh>
    </group>
  );
}

export default Akustik_Yamaha;
useGLTF.preload("/Akustik_Yamaha.glb");
