/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ./public/Elektrik.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { UseCustomization } from "../context/ColorContext";
import { UseTexture } from "../context/TextureContext";
import { TextureLoader } from "three";

export function Elektrik(props) {
  const { nodes, materials } = useGLTF("/Elektrik.glb");
  const ColorContext = UseCustomization();
  const { Tuner, Neck, Nut, Fret, FretBoard, Body, Bridge, BridgeNut } =
    ColorContext;
  const bridgenut = useRef();
  const fret = useRef();
  const bridge = useRef();
  const nut = useRef();
  const body = useRef();
  const neck = useRef();
  const tuner = useRef();
  const fretboard = useRef();
  const {
    TunerTxt,
    FretTxt,
    FretBoardTxt,
    NeckTxt,
    NutTxt,
    BodyTxt,
    BridgeTxt,
    BridgeNutTxt,
  } = UseTexture();

  useEffect(() => {
    const loadTexture = async () => {
      if (TunerTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(TunerTxt);
          tuner.current.map = texture;
          tuner.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [TunerTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NeckTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NeckTxt);
          neck.current.map = texture;
          neck.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NeckTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BodyTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BodyTxt);
          body.current.map = texture;
          body.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BodyTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretBoardTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretBoardTxt);
          fretboard.current.map = texture;
          fretboard.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [FretBoardTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (FretTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(FretTxt);
          fret.current.map = texture;
          fret.current.needsUpdate = true;
        } catch (error) {}
      }
    };
    loadTexture();
  }, [FretTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (NutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(NutTxt);
          nut.current.map = texture;
          nut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [NutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeNutTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeNutTxt);
          bridgenut.current.map = texture;
          bridgenut.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeNutTxt]);

  useEffect(() => {
    const loadTexture = async () => {
      if (BridgeTxt) {
        try {
          const textureLoader = new TextureLoader();
          const texture = await textureLoader.loadAsync(BridgeTxt);
          bridge.current.map = texture;
          bridge.current.needsUpdate = true;
        } catch {}
      }
    };
    loadTexture();
  }, [BridgeTxt]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Bridge001.geometry}
        material={nodes.Bridge001.material}
        position={[0, -1.689, 0.326]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial {...props} color={Bridge.color} ref={bridge} />
      </mesh>
      <mesh
        geometry={nodes.Nut012.geometry}
        material={nodes.Nut012.material}
        position={[-0.232, -1.676, 0.331]}
        rotation={[-Math.PI / 2, 1.369, Math.PI]}
      >
        <meshStandardMaterial {...props} color={Nut.color} ref={nut} />
      </mesh>
      <mesh
        geometry={nodes.BridgeNut.geometry}
        material={nodes.BridgeNut.material}
        position={[0.095, -1.414, 0.349]}
        rotation={[0, 0, 0.117]}
      >
        <meshStandardMaterial
          {...props}
          color={BridgeNut.color}
          ref={bridgenut}
        />
      </mesh>
      <mesh
        geometry={nodes.Neck.geometry}
        material={nodes.Neck.material}
        position={[-0.033, -0.487, 0.178]}
      >
        <meshStandardMaterial {...props} color={Neck.color} ref={neck} />
      </mesh>
      <mesh
        geometry={nodes.FretBoard.geometry}
        material={nodes.FretBoard.material}
        position={[0.191, -0.266, -0.037]}
      >
        <meshStandardMaterial
          {...props}
          color={FretBoard.color}
          ref={fretboard}
        />
      </mesh>
      <mesh
        geometry={nodes.Fret.geometry}
        material={nodes.Fret.material}
        position={[-0.019, -0.52, 0.256]}
      >
        <meshStandardMaterial {...props} color={Fret.color} ref={fret} />
      </mesh>
      <mesh
        geometry={nodes.Tuner008.geometry}
        material={nodes.Tuner008.material}
        position={[-0.456, 1.647, -0.012]}
        rotation={[-0.632, -0.048, -3.108]}
      >
        <meshStandardMaterial {...props} color={Tuner.color} ref={tuner} />
      </mesh>
      <mesh
        geometry={nodes.Body.geometry}
        material={nodes.Body.material}
        position={[0.043, -1.318, 0.288]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <meshStandardMaterial {...props} color={Body.color} ref={body} />
      </mesh>
    </group>
  );
}

export default Elektrik;
useGLTF.preload("/Elektrik.glb");
